#change configfile to point to experiment_config.yaml for this experiment
#change mkdir, --output and --error to point to log folder for this experiment
#change mail-user, mail-type to point to your email
#can change default resources or set-resources as needed


snakefile: Snakefile
use-conda: True
conda-frontend: mamba
rerun-incomplete: True
restart-times: 1
jobs: 10
latency-wait: 30
keep-going: True
configfile: ./experiment_info.yaml
conda-prefix: ~/miniconda3/envs/accusnv
reason: True
# dryrun: True
# unlock: True


#note that resource names should use underscore _ instead of dash -

default-resources:
   - cpus_per_task=1
   - mem=100000

set-resources:
   # make_data_links
   #- make_data_links:partition="sched_mit_hill"
   # cutadapt
   - cutadapt:cpus_per_task=1
   # sickle
   - sickle:cpus_per_task=1
   # bowtie2
   - bowtie2:cpus_per_task=1
   # sam2bam
   - sam2bam:cpus_per_task=1
   # mpileup2vcf
   - mpileup2vcf:cpus_per_task=1
   # pileup2diversity_matrix
   - pileup2diversity_matrix:cpus_per_task=1
   # variants2positions
   - variants2positions:cpus_per_task=1
   # combine_positions
   - combine_positions:cpus_per_task=1
   # build_data_links
   - build_data_links:cpus_per_task=1
   # kraken2
   - kraken2:cpus_per_task=20
   # spades
   - spades:cpus_per_task=16
   # prokka
   - prokka:cpus_per_task=16
